nameOverride: promops

##### grafana #####
grafana:
  enabled: false

##### prometheus-operator #####
prometheusOperator:
  priorityClassName: addons-critical
prometheus:
  podDisruptionBudget:
    enabled: true
  prometheusSpec:
    priorityClassName: addons-critical
    # QUESTION: enable to Prometheus scrape globally???
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    thanos:
      # Ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#thanosspec
      baseImage: quay.io/thanos/thanos
      version: v0.7.0
      objectStorageConfig:
        name: thanos-objstore-config
        key:  thanos.yaml
alertmanager:
  podDisruptionBudget:
    enabled: true
  alertmanagerSpec:
    priorityClassName: addons-critical

##### kube-state-metrics #####
kube-state-metrics:
  priorityClassName: addons-critical
  podSecurityPolicy:
    enabled: true
  # prometheus.monitor.enabled

##### prometheus-node-exporter #####
prometheus-node-exporter:
  priorityClassName: addons-critical
  # prometheus.monitor.enabled
