nameOverride: tivan
priorityClassName: addons-critical
# image: docker.elastic.co/kibana/kibana
# imageTag: 6.8.3

elasticsearchHosts: http://elasticsearch.host:9200
kibanaConfig:
  kibana.yml: |
    # Suppress all access logging other than error messages
    logging.quiet: true
    elasticsearch.username: kibana
    elasticsearch.password: supersecret

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    # kubernetes.io/ingress.class: nginx
  hosts:
  - logging.kites.rocks
  tls:
  - secretName: logging.kites.rocks-tls
    hosts:
    - logging.kites.rocks
