apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: theseus-jaeger
spec:
  strategy: production
  # allInOne: {}
  # sampling: {}

  ### Components configs
  agent:
    strategy: DaemonSet
  # collector: {}
  # query: {}
  # ingester: {}
  # ui: {}

  ### Storage configs
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch.host:9200
        username: jaeger
        password: jaeger-secure-password

  ### Networking configs
  ingress:
    # Kubernetes Ingress disable for now
    # Because alot of features are missing
    enabled: false

  ### Finer-grained configs
  # ref: https://www.jaegertracing.io/docs/1.14/operator/#finer-grained-configuration
  # annotations: {}
  # labels: {}
  # resources: {}
  # affinity: {}
  # tolerations: {}
  # serviceAccount: jaeger-sa
  # securityContext: {}
  # volumeMounts: []
  # volumes: []
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
  labels:
    app: theseus-jaeger
  name: theseus-jaeger
spec:
  rules:
  - host: tracing.kites.rocks
    http:
      paths:
      - backend:
          serviceName: theseus-jaeger-query
          servicePort: 16686
  tls:
  - hosts:
    - tracing.kites.rocks
    secretName: tracing.kites.rocks-tls
