apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: foobar-jaeger
spec:
  strategy: production
  # allInOne: {}
  # sampling: {}

  ### Components configs
  agent:
    strategy: DaemonSet
  # collector: {}
  # query: {}
  # ingester: {}
  # ui: {}

  ### Storage configs
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch.host:9200

  ### Networking configs
  # ingress: {} # Kubernetes Ingress

  ### Finer grained configs
  # ref: https://www.jaegertracing.io/docs/1.14/operator/#finer-grained-configuration
  # annotations: {}
  # labels: {}
  # resources: {}
  # affinity: {}
  # tolerations: {}
  # serviceAccount: jaeger-sa
  # securityContext: {}
  # volumeMounts: []
  # volumes: []
